package org.netbeans.rest.application.config;

import java.util.Set;
import javax.ws.rs.core.Application;

/**
 *
 * @author pierregauthier
 *
 */
@javax.ws.rs.ApplicationPath("catalogManagement")
public class ApplicationConfig extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        return getRestResourceClasses();
    }

    /*
     * Do not modify this method. It is automatically generated by NetBeans REST support.
     */
    private Set<Class<?>> getRestResourceClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        resources.add(org.tmf.dsmapi.catalog.service.JacksonConfigurator.class);
        resources.add(org.tmf.dsmapi.catalog.service.catalog.CatalogFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.category.CategoryFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.category.CategoryInCatalogIdFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.category.CategoryInCatalogIdVersionFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.productOffering.ProductOfferingFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.productOffering.ProductOfferingInCatalogIdFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.productOffering.ProductOfferingInCatalogIdVersionFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.productOfferingPrice.ProductOfferingPriceFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.productOfferingPrice.ProductOfferingPriceInCatalogIdFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.productOfferingPrice.ProductOfferingPriceInCatalogIdVersionFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.productSpecification.ProductSpecificationFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.productSpecification.ProductSpecificationInCatalogIdFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.productSpecification.ProductSpecificationInCatalogIdVersionFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.resourceCandidate.ResourceCandidateFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.resourceCandidate.ResourceCandidateInCatalogIdFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.resourceCandidate.ResourceCandidateInCatalogIdVersionFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.resourceSpecification.ResourceSpecificationFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.resourceSpecification.ResourceSpecificationInCatalogIdFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.resourceSpecification.ResourceSpecificationInCatalogIdVersionFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.serviceCandidate.ServiceCandidateFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.serviceCandidate.ServiceCandidateInCatalogIdFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.serviceCandidate.ServiceCandidateInCatalogIdVersionFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.serviceSpecification.ServiceSpecificationFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.serviceSpecification.ServiceSpecificationInCatalogIdFacadeREST.class);
        resources.add(org.tmf.dsmapi.catalog.service.serviceSpecification.ServiceSpecificationInCatalogIdVersionFacadeREST.class);
        // following code can be used to customize Jersey 1.x JSON provider:
        try {
            Class jacksonProvider = Class.forName("org.codehaus.jackson.jaxrs.JacksonJsonProvider");
            resources.add(jacksonProvider);
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(getClass().getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        return resources;
    }

}
